env:
  browser: true
  es2023: true
  webextensions: true
parser: "@typescript-eslint/parser"
plugins:
  - solid
extends:
  - standard-with-typescript
  - "plugin:solid/typescript"
parserOptions:
  "project":
    - "./tsconfig.json"
  ecmaVersion: latest
  sourceType: module
rules:
  "@typescript-eslint/explicit-function-return-type": 0
  "@typescript-eslint/strict-boolean-expressions":
    - error
    - allowNullableBoolean: true
      allowNullableString: true
  no-unused-vars:
    - error
    - ignoreRestSiblings: true
      varsIgnorePattern: '^_'
      argsIgnorePattern: '^_'
  "@typescript-eslint/comma-dangle":
    - "error"
    - "always-multiline"
  "@typescript-eslint/space-before-function-paren": 0
  "@typescript-eslint/no-dynamic-delete": 0
