version: 3

tasks:
  dev:firefox:
    env:
      VITE_RUN_MODE: dev
    cmds:
      - fwatcher --exec "pnpm run dev:firefox" --ext ".jsx" --ext ".js" --ext ".json" --ext ".tsx" --ext ".ts" --exclude-dir "dist"

  dev:chrome:
    cmds:
      # - fwatcher -d "$PWD" -e "pnpm run build" --ext ".jsx"
      - fwatcher -e "pnpm run dev:chrome" --ext ".jsx" --ext ".js" --exclude-dir "dist"

  build:
    cmds:
      - npm run build

  zip:build:
    cmds:
      - task: build
      - |+
        pushd dist
        zip -r ../control-center.zip *
        popd

  zip:source:
    cmds:
      - |+
        dir_name=$(basename $PWD)
        pushd ..
        zip -r control-center-source.zip $dir_name -x "$dir_name/node_modules/*" -x "$dir_name/dist/*" -x "$dir_name/.git/*" -x "$dir_name/.idea/*"
        mv ./control-center-source.zip ./$dir_name/control-center-source.zip
        popd
